import './selected/globals';
import { stubProviders } from './selected/stubs';
import { Component, createNgModule, NgModuleRef, ViewChild, ViewContainerRef } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

interface CurrentSelection {
  component: string;
  root: string;
  strategy: 'standalone' | 'module';
  revision: number;
  error: string | null;
  inputValues?: Record<string, unknown>;
  requiredInputs?: string[];
}

/**
 * Minimal mount point. The selected component is created through the root's
 * ViewContainerRef — the standard dynamic-component path — so the renderer and
 * environment injector chains are the same as any real application.
 */
@Component({
  selector: 'rc-root',
  standalone: true,
  template: '<ng-container #host></ng-container>',
})
class RootComponent {
  @ViewChild('host', { read: ViewContainerRef, static: true })
  host!: ViewContainerRef;

  ngOnInit(): void {
    mountPoint = this.host;
  }
}

// Theme toggle (C30): the workspace design system scopes its dark theme to
// `body.dark` / `body.fdark` (applied by the app's ThemeService). The host
// mirrors it with a `d` keybind, persisted across hot-swap reloads.
const THEME_KEY = 'rc-theme-dark';

function applyTheme(): void {
  const dark = localStorage.getItem(THEME_KEY) === '1';
  document.body.classList.toggle('dark', dark);
  document.body.classList.toggle('fdark', dark);
}

let mountPoint: ViewContainerRef | null = null;
let moduleRef: NgModuleRef<unknown> | null = null;
let lastRevision = -1;

function showError(message: string): void {
  document.body.innerHTML = '';
  const pre = document.createElement('pre');
  pre.style.cssText = 'color:#b91c1c;font:14px/1.6 monospace;padding:24px;white-space:pre-wrap;';
  pre.textContent = message;
  document.body.appendChild(pre);
}

function clearView(): void {
  mountPoint?.clear();
  if (moduleRef) {
    moduleRef.destroy();
    moduleRef = null;
  }
}

async function mount(current: CurrentSelection): Promise<void> {
  // entry.ts is regenerated by render-component on every applied selection;
  // the dev server rebuilds it and this page reloads, so this import always
  // resolves to the freshly compiled component (R7 hot-swap).
  const entry: any = await import('./selected/entry');
  const componentClass: any = Object.values(entry).find((x: any) => x && x.ɵcmp);
  if (!componentClass || !mountPoint) {
    showError('No component class found in the generated entry module.');
    return;
  }
  clearView();

  if (current.strategy === 'module') {
    const moduleClass: any = Object.values(entry).find((x: any) => x && x.ɵmod);
    if (!moduleClass) {
      showError('Strategy is "module" but the entry exports no NgModule class.');
      return;
    }
    // D3: mount through the component's own NgModule context.
    moduleRef = createNgModule(moduleClass as any, mountPoint.injector);
    const ref = mountPoint.createComponent(componentClass as any, { ngModuleRef: moduleRef });
    provideInputs(ref, current);
  } else {
    const ref = mountPoint.createComponent(componentClass as any);
    provideInputs(ref, current);
  }
}

// C32/C28: apply the fictional typed values generated from the workspace
// types, then give any remaining required input an empty `{}` placeholder so
// the first CD pass doesn't throw NG0950. Inputs land in the same tick as
// creation, before the component's template is change-detected.
function provideInputs(ref: any, current: CurrentSelection): void {
  for (const [name, value] of Object.entries(current.inputValues ?? {})) {
    try {
      ref.setInput(name, value);
    } catch {
      // best effort: input may not exist on this component
    }
  }
  for (const name of current.requiredInputs ?? []) {
    if (!(name in (current.inputValues ?? {}))) {
      try {
        ref.setInput(name, {});
      } catch {
        // best effort
      }
    }
  }
}

window.addEventListener('keydown', (e: KeyboardEvent) => {
  const target = e.target as HTMLElement | null;
  if (target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement) {
    return;
  }
  if (e.key.toLowerCase() === 'd') {
    const dark = !document.body.classList.contains('dark');
    localStorage.setItem(THEME_KEY, dark ? '1' : '0');
    applyTheme();
  }
});

async function reloadWhenSettled(): Promise<void> {
  const deadline = Date.now() + 10_000;
  while (Date.now() < deadline) {
    try {
      const res = await fetch('/api/ready');
      const state = (await res.json()) as { pending: boolean; ngExited: boolean };
      if (state.ngExited) {
        showError('The Angular dev-server process exited unexpectedly. Restart render-component (details in the logs panel).');
        return;
      }
      if (!state.pending) {
        break;
      }
    } catch {
      // control API hiccup: keep waiting
    }
    await new Promise((r) => setTimeout(r, 300));
  }
  location.reload();
}

async function main(): Promise<void> {
  applyTheme();
  // 1) Pin the current revision BEFORE subscribing to /api/events. The SSE
  //    stream echoes the current revision to every (re)connect; revisions are
  //    monotonic and we compare with `>`, so that echo is a guaranteed no-op
  //    instead of a spurious reload (this was the infinite-refresh loop).
  const res = await fetch('/api/current');
  const current = (await res.json()) as CurrentSelection;
  lastRevision = current.revision;

  if (current.error) {
    showError(current.error);
    return;
  }

  // 2) Subscribe: only a STRICTLY greater revision (a real selection change)
  //    triggers the reload — and it waits for the dev-server build to settle
  //    (C31) so we never fetch a bundle mid-write.
  const events = new EventSource('/api/events');
  events.onmessage = (e: MessageEvent) => {
    const revision = Number(e.data);
    if (revision > lastRevision) {
      lastRevision = revision;
      void reloadWhenSettled();
    }
  };

  // 3) Mount. If the entry chunk fails transiently (e.g. fetched mid-rebuild
  //    right after a hot-swap), retry exactly once via a full reload — the
  //    sessionStorage flag makes the retry non-looping.
  try {
    await mount(current);
    sessionStorage.removeItem('rc-mount-retried');
  } catch (err: unknown) {
    if (!sessionStorage.getItem('rc-mount-retried')) {
      sessionStorage.setItem('rc-mount-retried', '1');
      location.reload();
      return;
    }
    sessionStorage.removeItem('rc-mount-retried');
    showError(String((err as Error)?.stack ?? err));
  }
}

// stubProviders carries DI stubs generated per selection (e.g. NgbActiveModal
// for modal-content components) — an empty array for normal components.
bootstrapApplication(RootComponent, { providers: stubProviders })
  .then(() => main())
  .catch((err: unknown) => showError(String((err as Error)?.stack ?? err)));
